DROP DATABASE IF EXISTS Testing_System;
CREATE DATABASE Testing_System;
USE Testing_System;
DROP TABLE IF EXISTS Department;
CREATE TABLE Department (
DepartmentID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DepartmentName VARCHAR(50) NOT NULL UNIQUE KEY
);
DROP TABLE IF EXISTS Position;
CREATE TABLE `Position` (
PositionID TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
PositionName ENUM('DEV','TEST','Scrum Master','PM') NOT NULL UNIQUE KEY
);
DROP TABLE IF EXISTS Account;
CREATE TABLE `Account` (
AccountID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Email			VARCHAR(50) NOT NULL UNIQUE KEY,
Username		VARCHAR(50) NOT NULL UNIQUE KEY,
FullName		VARCHAR(50) NOT NULL,
DepartmentID	TINYINT UNSIGNED NOT NULL,
PositionID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATETIME DEFAULT NOW(),
FOREIGN KEY(DepartmentID) REFERENCES Department(DepartmentID),
FOREIGN KEY(PositionID) REFERENCES `Position`(PositionID)
);
-- INSERT INTO Department(DepartmentName) 
-- VALUE					('Sale');
-- INSERT INTO Department(DepartmentName) 
-- VALUE					('Marketing');
-- INSERT INTO Department(DepartmentName) 
-- VALUE					('BOD');
INSERT INTO Department(DepartmentName)
VALUES			
						( 'BOD'),
                        ( 'Marketing'),
                        ( 'Sale'),
                        ( 'HR'),
                        ( 'IT');
INSERT INTO Position	(PositionName) 
VALUES 					( 'Dev'),
						( 'Test'),
						( 'Scrum Master'),
						( 'PM'); 
DROP TABLE IF EXISTS `Group`;
CREATE TABLE `Group` (
GroupID			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
GroupName		VARCHAR(50) NOT NULL UNIQUE KEY,
CreatorID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATETIME DEFAULT NOW(),
FOREIGN KEY(CreatorID) REFERENCES `Account`(AccountID)
);
DROP TABLE IF EXISTS GroupAccount;
CREATE TABLE GroupAccount (
GroupID			TINYINT UNSIGNED NOT NULL,
AccountID		TINYINT UNSIGNED NOT NULL,
JoinDate		DATETIME DEFAULT NOW(),
FOREIGN KEY(GroupID) REFERENCES `Group`(GroupID)
);
DROP TABLE IF EXISTS TypeQuestion;
CREATE TABLE TypeQuestion (
TypeID 			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
TypeName 		ENUM('Essay','Multiple-Choice') NOT NULL UNIQUE KEY
);
DROP TABLE IF EXISTS CategoryQuestion;
CREATE TABLE CategoryQuestion(
CategoryID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
CategoryName	VARCHAR(50) NOT NULL UNIQUE KEY
);
DROP TABLE IF EXISTS Question;
CREATE TABLE Question (
QuestionID		TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Content			VARCHAR(50) NOT NULL,
CategoryID		TINYINT UNSIGNED NOT NULL,
TypeID			TINYINT UNSIGNED NOT NULL,
CreatorID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATETIME DEFAULT NOW(),
FOREIGN KEY(CategoryID) REFERENCES CategoryQuestion(CategoryID),
FOREIGN KEY(TypeID) REFERENCES TypeQuestion(TypeID),
FOREIGN KEY(CreatorID) REFERENCES `Account`(AccountID) 
);
DROP TABLE IF EXISTS Exam;
CREATE TABLE Exam (
ExamID			TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
Code			CHAR(10) NOT NULL,
Title			VARCHAR(50) NOT NULL,
CategoryID		TINYINT UNSIGNED NOT NULL,
Duration		TINYINT UNSIGNED NOT NULL,
CreatorID		TINYINT UNSIGNED NOT NULL,
CreateDate		DATETIME DEFAULT NOW(),
FOREIGN KEY(CategoryID) REFERENCES CategoryQuestion(CategoryID),
FOREIGN KEY(CreatorID) REFERENCES `Account`(AccountId)
);
DROP TABLE IF EXISTS ExamQuestion;
CREATE TABLE ExamQuestion (
ExamID			TINYINT UNSIGNED NOT NULL,
QuestionID		TINYINT UNSIGNED NOT NULL,
FOREIGN KEY(QuestionID) REFERENCES Question(QuestionID),
FOREIGN KEY(ExamID) REFERENCES Exam(ExamID)
);



